name: Clean Astra env

on:
  workflow_dispatch: {}
  schedule:
    - cron: "*/4 * * * *"

jobs:
  clean:
    name: Clean Astra env
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Clean AstraDB databases older than 1 day
        uses: nicoloboschi/cleanup-astradb-env@v1
        with:
          token: ${{ secrets.TESTS_ASTRA_DEV_DB_TOKEN }}
          wait: false
